#!/bin/bash
# EXAMPLE: ./build
# EXAMPLE: ./build --debug

set -eu

if test ! $(which MSBuild.exe)
then
    echo 'MSBuild.exe にパスを通してください。' >&2
    exit 1
fi

build() {
    CONFIG="$1"

    MSBuild.exe '-t:Build' "$CONFIG"
}

FLAG="${1:-''}"

./fmt || :

build '-p:Configuration=Debug;Platform=x86'
if test "$FLAG" = '--debug'
then
    exit 0
fi

build '-p:Configuration=Debug;Platform=x64'
build '-p:Configuration=Release;Platform=x86'
build '-p:Configuration=Release;Platform=x64'
