#!/bin/bash
# Prerequisites:
#   clang-format をインストールすること。
#   Visual Studio 2019 がインストール済みなら次の位置にあるので、パスを通せば OK:
#       "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin"

set -eu

SRC="./hsp3-vartype-trie"

clang-format -style=file -i "$SRC/**.cpp" "$SRC/**.h"
