#!/bin/bash
# VSCode 拡張機能をビルド・インストールする。
# これを実行する前に、LSP サーバーをビルドしておくこと。

set -eu

# 前回生成したファイルを削除する。
if test -f ham.vsix
then
    rm ham.vsix
fi

# 配布用ディレクトリに必要なファイルを入れる。
cp ../target/release/ham ./dist/ham

# 拡張機能をビルドする。
npm run build
npm run vsce-package

# ローカルにインストールする。
./uninstall || :
code --install-extension ham.vsix
