#!/bin/bash
# Build compiler before this.

set -eux

if [[ -f ham.vsix ]]
then
    rm ham.vsix
fi

cp ../target/release/ham-lsp ./out/ham-lsp

npm install
npm run build
npm run vsce:package

./uninstall || :
code --install-extension ham.vsix
