#!/bin/bash

set -eux

# ビルドする。
cargo build -p ham-core -p ham-lsp-server-exe

# DLL は32ビットでビルドする。
cargo build -p ham-lsp-server-dll --target i686-pc-windows-msvc

(
    cd vscode-ext
    npm run build
)
