#!/bin/bash
# VSCode 拡張機能をビルド・インストールする。

set -eu

# 必要なツールがインストールされていることを検査する。
cargo --version
npm --version
code --version

# LSP サーバーをリリースモードでビルドする。
cargo build --release

# 拡張機能のインストール
(
    cd vscode-ext
    ./install
)
