#!/bin/bash
# Build and install VSCode extension.

set -eux

# Check.
cargo --version
yarn --version
code --version

# Build the compiler for release.
cargo build --release

# Build VSCode extension.
(cd vscode-ext && ./install)
