#!/bin/bash
# ユーザーディレクトリの下に ~/bin を作成して、そこにパスが通しておくこと。
# ginger コマンドをインストールして、パスを通しておくこと。

set -eu

(
    cd ..
    cargo build -p ham-sdk --target i686-pc-windows-msvc
    cp target/i686-pc-windows-msvc/debug/ham_sdk.dll ~/bin/ham_sdk.dll
)

ginger run app_main.hsp
