[package]
name = "tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Ctrl+C を処理するため
# https://github.com/Detegr/rust-ctrlc
ctrlc = { version = "3.0", features = ["termination"] }
